server:
  port: 8082
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: person-microservice

#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        health-check-tls-skip-verify: true
#        health-check-url: https://localhost:${server.port}/actuator/health

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
